import librosa
import numpy as np

# Path to the WAV file generated by the Web App
path = "C:\Users\paulj\OneDrive\Desktop\sound clips\KingOfKingsChorus.wav"

# 1. Load exactly as the app does
y, sr = librosa.load(path, sr=44100, mono=True, offset=47.0, duration=29.0)

# 2. Check the peak (The Discrepancy Point)
max_abs = np.max(np.abs(y))
print(f"PyQt WAV Peak (max_abs): {max_abs:.7f}")

# 3. Process first 5 resampled points
target_indices = np.linspace(0, len(y) - 1, 200000).astype(int)
y_resampled = (y / max_abs)[target_indices]
print(f"PyQt WAV Resampled First 5: {y_resampled[:5].tolist()}")